DEBUG:
  DISABLE_ROILOSS: True

MODEL:
  DEVICE: "cuda"
  RPN_ONLY: False
DATASETS:
  TRAIN: ("suncg_train", "suncg_val")
  TEST: ("suncg_test",)
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  EPOCHS: 300
  EPOCHS_BETWEEN_TEST: 300
  IMS_PER_BATCH: 1
  BASE_LR: 0.02
  WEIGHT_DECAY: 0.000
  STEPS: (1000,)
  CHECKPOINT_PERIOD: 200
  WARMUP_ITERS: 40
OUTPUT_DIR: "results_bs1_l2_rpn"
TEST:
  IMS_PER_BATCH: 1
