DEBUG:
  DISABLE_ROILOSS: False

MODEL:
  DEVICE: "cuda"
  RPN_ONLY: False
  META_ARCHITECTURE: "SparseRCNN"
  BACKBONE:
    CONV_BODY: "Sparse-R-50-FPN"
    OUT_CHANNELS: 128
  RPN:
    USE_FPN: True
    RPN_HEAD: "SingleConvRPNHead_Sparse3D"
    ANCHOR_SIZES_3D: [[0.2,0.5,3], [0.4,1.5,3], [0.6,2.5,3]]
    YAWS:  (0, -1.57, -0.785, 0.785)
    PRE_NMS_TOP_N_TRAIN: 1000
    POST_NMS_TOP_N_TRAIN: 1000
    PRE_NMS_TOP_N_TEST: 600
    POST_NMS_TOP_N_TEST: 600
    FPN_POST_NMS_TOP_N_TEST: 1000
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    #POOLER_SCALES: (0.5,0.25, 0.125)
  RPN_SCALES_FROM_TOP: [4,3,2] 
  LOSS:
    YAW_MODE: 'Diff'
SPARSE3D:
  nPlanesFront:  [32, 64, 64, 128, 128, 128, 256, 256, 256, 256]
  KERNEL: [[2,2,4], [2,2,4], [2,2,4], [1,1,4], [2,2,4], [2,2,1], [2,2,1],[2,2,1],[2,2,1]]
  STRIDE: [[2,2,2], [2,2,4], [2,2,4], [1,1,4], [2,2,1], [2,2,1], [2,2,1],[2,2,1],[2,2,1]]
  VOXEL_FULL_SCALE: [2048, 2048, 514]
  VOXEL_SCALE: 50
  SCENE_SIZE: [8,8,5]
DATASETS:
  TRAIN: ("suncg_train", "suncg_val")
  TEST: ("suncg_test",)
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  EPOCHS: 300
  EPOCHS_BETWEEN_TEST: 300
  IMS_PER_BATCH: 1
  BASE_LR: 0.01
  WEIGHT_DECAY: 0.000
  STEPS: (1000,)
  CHECKPOINT_PERIOD: 200
  WARMUP_ITERS: 40
OUTPUT_DIR: "results_bs1_fpn3_l1"
TEST:
  IMS_PER_BATCH: 1
