DEBUG:
  DISABLE_ROILOSS: False
  eval_in_train: True
INPUT:
  #CLASSES: ['background', 'wall']
  CLASSES: ['background', 'wall', 'door', 'window']
  ELEMENTS: ['xyz', 'color', 'normal']
MODEL:
  DEVICE: "cuda"
  RPN_ONLY: False
  META_ARCHITECTURE: "SparseRCNN"
  BACKBONE:
    CONV_BODY: "Sparse-R-50-FPN"
    OUT_CHANNELS: 128
  RPN:
    USE_FPN: True
    RPN_HEAD: "SingleConvRPNHead_Sparse3D"
    ANCHOR_SIZES_3D: [[0.4,1.5,1.5], [0.2,0.5,3], [0.4,1.5,3], [0.6,2.5,3]]
    YAWS:  (0, -1.57, -0.785, 0.785)
    PRE_NMS_TOP_N_TRAIN: 1000
    POST_NMS_TOP_N_TRAIN: 1000
    PRE_NMS_TOP_N_TEST: 600
    POST_NMS_TOP_N_TEST: 600
    FPN_POST_NMS_TOP_N_TEST: 1000
    RPN_SCALES_FROM_TOP: [4,3,2] 
    RPN_3D_2D_SELECTOR: [1,3,4,5]
    YAW_THRESHOLD: 0.7
    FG_IOU_THRESHOLD: 0.55 #  0.7
    BG_IOU_THRESHOLD: 0.2 # 0.3
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: (7,7,3)
    POOLER_SCALES_FROM_TOP: (4,3)
  LOSS:
    YAW_MODE: 'Diff'
SPARSE3D:
  nPlanesFront:  [32, 64, 64, 128, 128, 128, 256, 256, 256]
  KERNEL: [[2,2,2], [2,2,2], [2,2,2], [2,2,2], [2,2,2],[2,2,2],[2,2,2],[2,2,2]]
  STRIDE: [[2,2,2], [2,2,2], [2,2,2], [2,2,2], [2,2,2],[2,2,2],[2,2,2],[2,2,2]]
  VOXEL_FULL_SCALE: [512,512,256]
  VOXEL_SCALE: 50
  SCENE_SIZE: [8,8,5]
DATASETS:
  TRAIN: ("suncg_train", "suncg_val")
  TEST: ("suncg_test",)
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  EPOCHS: 300
  EPOCHS_BETWEEN_TEST: 300
  IMS_PER_BATCH: 8
  BASE_LR: 0.01
  WEIGHT_DECAY: 0.000
  LR_STEP_EPOCHS: (10,)
  CHECKPOINT_PERIOD_EPOCHS: 20
  WARMUP_EPOCHS: 0.7
OUTPUT_DIR: "res_3d_bs8_wdw_augroi"
TEST:
  IMS_PER_BATCH: 1
