
MODEL:
  DEVICE: "cuda"
  RPN_ONLY: False
  META_ARCHITECTURE: "SparseRCNN"
  #WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  BACKBONE:
    CONV_BODY: "Sparse-R-50-FPN"
    OUT_CHANNELS: 128
  RPN:
    USE_FPN: True
    RPN_HEAD: "SingleConvRPNHead_Sparse3D"
    ANCHOR_SIZES_3D: [[0.2,1,3], [0.5,2,3], [1,3,3]]
    YAWS:  (0, -1.57, -0.785, 0.785)
    #YAWS:  (0, -1.57)
    FG_IOU_THRESHOLD: 0.6
    BG_IOU_THRESHOLD: 0.3
    YAW_THRESHOLD: 0.7
    PRE_NMS_TOP_N_TRAIN: 2000
    POST_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
  ROI_HEADS:
    USE_FPN: True
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
  FPN_SCALES: [5,6,7]
  LOSS:
    YAW_MODE: 'Diff'
SPARSE3D:
  nPlanesFront:  [32, 64, 64, 128, 128, 128, 256, 256, 256, 256]
  KERNEL: [[2,2,4], [2,2,4], [2,2,4], [1,1,4], [2,2,4], [2,2,1], [2,2,1],[2,2,1],[2,2,1]]
  STRIDE: [[2,2,2], [2,2,4], [2,2,4], [1,1,4], [2,2,1], [2,2,1], [2,2,1],[2,2,1],[2,2,1]]
  VOXEL_FULL_SCALE: [2048, 2048, 514]
  VOXEL_SCALE: 50
DATASETS:
  TRAIN: ("suncg_train", "suncg_val")
  TEST: ("suncg_test",)
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  EPOCHS: 300
  EPOCHS_BETWEEN_TEST: 300
  IMS_PER_BATCH: 1
  BASE_LR: 0.01
  WEIGHT_DECAY: 0.000
  STEPS: (100000000,)
  CHECKPOINT_PERIOD: 180
  WARMUP_ITERS: 80
OUTPUT_DIR: "results_nms1_difyl"
TEST:
  IMS_PER_BATCH: 2
